apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ${{ values.teamName }}
  title: ${{ values.teamTitle }}
  description: ${{ values.teamDescription }}
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: ${{ values.teamType }}
  parent: ${{ values.parentGroup }}
  children: []
  members: []
