apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: SPA Angular con Angular CLI
  tags:
    - angular
    - typescript
  annotations:
    github.com/project-slug: ${{ values.repoOwner }}/${{ values.name }}
spec:
  type: website
  lifecycle: experimental
  owner: group:default/platform-team
